### PR TITLE
fix SDWebImageOptions error

### PR DESCRIPTION
**Pull request by pepsikirk**
fix SDWebImageOptions error

### CODE REVIEW

**Comment by dreampiggy** [comment]
I don't think this fix is useful.

Actually, this firstly convert `SDWebImageOptions` into `SDImageCacheOption`, and then convert `SDImageCacheOptions` into `SDWebImageOptions`

Why do this stupid useless thing ? Since the YYCache support does not need any `SDImageCacheOption` API, so just don't do any convert is enough.

Remove this code:
https://github.com/SDWebImage/SDWebImageYYPlugin/pull/14/files#diff-f9faf5c364fdaf67ddbd26839c3ad3615d2687dd48f0a8e1e02890e11ca0a22eR81

**Comment by pepsikirk** [comment]
> I don't think this fix is useful.
> 
> Actually, this firstly convert `SDWebImageOptions` into `SDImageCacheOption`, and then convert `SDImageCacheOptions` into `SDWebImageOptions`
> 
> Why do this stupid useless thing ? Since the YYCache support does not need any `SDImageCacheOption` API, so just don't do any convert is enough.
> 
> Remove this code: https://github.com/SDWebImage/SDWebImageYYPlugin/pull/14/files#diff-f9faf5c364fdaf67ddbd26839c3ad3615d2687dd48f0a8e1e02890e11ca0a22eR81

Please review the code where I've implemented the conversion. The options parameter required by the `SDImageCacheDecodeImageData` function needs to be of type `SDWebImageOptions`, whereas the options used in the current method are of type `SDImageCacheOptions`. Therefore, a conversion is necessary.

A similar conversion has also been performed in the `diskImageForKey:data:options` method within `SDImageCache`. I've made these modifications following the approach used in `SDImageCache`.

Thank you.

**Comment by dreampiggy** [comment]
> whereas the options used in the current method are of type SDImageCacheOptions. Therefore, a conversion is necessary

`current method are of type SDImageCacheOptions`

No. This method is not public API.

It does not need `SDImageCacheOptions` at all. Remove this method.

Or I can provide a PR for this changes.

**Comment by dreampiggy** [comment]
Replaced with #15, see that instead.

**Comment by pepsikirk** [comment]
> Replaced with #15, see that instead.

OK，This is indeed better.

**Pull request closed without merging**
